# Generated by Django 4.2.7 on 2024-04-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhiv_reestr_tmts_model',
            name='action',
            field=models.CharField(blank=True, max_length=105, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='arhiv_reestr_tmts_repair_model',
            name='action',
            field=models.CharField(blank=True, max_length=105, verbose_name='Действие'),
        ),
    ]
