# -*- coding: UTF-8 -*-

"""
Django settings for uchet_tmts project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os, inspect
import django_dyn_dt

import ldap
from django_auth_ldap.config import LDAPSearch, LDAPGroupQuery, GroupOfNamesType, PosixGroupType, LDAPSearchUnion

from django.contrib.messages import constants as messages

import logging

logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
# logger.setLevel(logging.WARNING)
logger.setLevel(logging.DEBUG)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['1.1.1.1', '127.0.0.1']


# Application definition

# приложение можно поставить в начало списка, чтобы template брались в первую очередь из его раздела
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_auth_users.apps.AppAuthUsersConfig',
    'laptop.apps.LaptopConfig',
    # 'printers.apps.PrintersConfig',

    'django_dyn_dt', # <-- NEW App
    'django_tables2',
    'django_select2',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 'django.contrib.auth.middleware.RemoteUserMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uchet_tmts.urls'

TEMPLATE_DIR_DATATB = os.path.join(BASE_DIR, "django_dyn_dt/templates") # <-- NEW App

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), TEMPLATE_DIR_DATATB],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uchet_tmts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "uchet_tmts",
        "USER": "sa",
        "PASSWORD": "password",
        "HOST": "127.0.0.1",
        "PORT": "1433",
        "OPTIONS": {"driver": "ODBC Driver 17 for SQL Server", 
        },
    },
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DYN_DB_PKG_ROOT = os.path.dirname( inspect.getfile( django_dyn_dt ) ) # <-- NEW App

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(DYN_DB_PKG_ROOT, "templates/static"),
]

LOGIN_REDIRECT_URL = '/'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-successs',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}





LDAP_IGNORE_CERT_ERRORS = True
AUTH_LDAP_START_TLS = False

AUTH_LDAP_SERVER_URI = 'ldap://site.ru'

AUTH_LDAP_AUTHORIZE_ALL_USERS = True
AUTH_LDAP_PERMIT_EMPTY_PASSWORD = True

# AUTH_LDAP_BIND_DN = 'cn=ldap,cn=admin,dc=site,dc=ru'
AUTH_LDAP_BIND_DN = 'ldap@site.ru'
AUTH_LDAP_BIND_PASSWORD = 'password'

AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
    LDAPSearch('ou=Admin,dc=site,dc=ru',ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch('ou=Users,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru',ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch('ou=Users,ou=SITE160,ou=BRN_56_63_144_175,dc=site,dc=ru',ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch('ou=Users,ou=FARMS,ou=SITE58,ou=BRN_56_63_144_175,dc=site,dc=ru',ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
)



AUTH_LDAP_GROUP_SEARCH = LDAPSearch('ou=Groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru',
ldap.SCOPE_SUBTREE, "(objectClass=Group)")
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")

## AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")

AUTH_LDAP_REQUIRE_GROUP = (
    LDAPGroupQuery("cn=WG_Access_TMTS_Admin,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru")|
    LDAPGroupQuery("cn=WG_Access_TMTS_Staf,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru")|
    LDAPGroupQuery("cn=WG_Access_TMTS_Active,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru")
)


AUTH_LDAP_USER_ATTR_MAP = {
        "username": "sAMAccountName",
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
        
        # "password": "userPassword",
}




# для нескольких групп используем формат списка - "is_staff": ["cn=WG_Access_PrintersFunc", "cn=WG_Admin_PrintersFunc"],
AUTH_LDAP_USER_FLAGS_BY_GROUP = { 
        "is_active": [                   
                      "cn=WG_Access_TMTS_Active,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru",
                      "cn=WG_Access_TMTS_Staf,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru",
                      "cn=WG_Access_TMTS_Admin,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru"],

        "is_staff": [                    
                     "cn=WG_Access_TMTS_Staf,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru",
                     "cn=WG_Access_TMTS_Admin,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru"],

        "is_superuser": ["cn=WG_Access_TMTS_Admin,ou=groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru",],
}

# AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")

# AUTH_LDAP_GROUP_SEARCH = LDAPSearch('ou=Groups,ou=SITE170,ou=BRN_56_63_144_175,dc=site,dc=ru',
# ldap.SCOPE_SUBTREE, "(objectClass=Group)")




AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_CACHE_TIMEOUT = 3600


# AUTH_LDAP_MIRROR_GROUPS = True  # Will sync ldap groups to django, if not exist
# AUTH_LDAP_MIRROR_GROUPS_EXCEPT except some groups we don't want to mirror in django


# AUTH_LDAP_PROFILE_ATTR_MAP = {
#         "home_directory": "homeDirectory"
# }
    




SESSION_COOKIE_AGE = 30 * 24 * 60 * 60      # Время жизни сессии в куках (указывается в секундах 30 дней)
# также можно настроить куки-name (название куки, в которой будет хранится ключ сессии) 
# и истечение сессии при закрытии браузера (по умолчанию false)

AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',

        ## 'django_remote_auth_ldap.backend.RemoteUserLDAPBackend',
)

DRAL_CHECK_DOMAIN = False

## AUTH_LDAP_CONNECTION_OPTIONS = { ldap.OPT_REFERRALS: 0}

DYNAMIC_DATATB = {
    # SLUG -> Import_PATH 
    'name_TMTS'  : "laptop.models.Name_TMTS_Model",
}
